name = "africa"
license = "MIT"
licenselink = "https://www.ulyssesmurja.com/LICENSE.md"
description = "Simple portfolio and blog Hugo Theme"
homepage = "https://www.ulyssesmurja.com/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Ulysses Ferreira Murja"
  homepage = "https://www.ulyssesmurja.com"
